'use client'

import './globals.css'
import { QueryClient, QueryClientProvider } from 'react-query'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchOnReconnect: false,
      retry: false
    },
  },
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='vh-100 bg-dark'>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}
